---
# handlers file for roles/ansible-htcondor
- name: restart condor
  service:
    name: condor
    state: restarted
- name: regenerate daemon idtoken
  command: "condor_token_create -identity condor@{{ condor_host }} -token /etc/condor/tokens.d/condor@{{ condor_host }}"
  notify: restart condor
